import { ProviderApplication } from '../models/application.model';
import { Provider } from '../models/provider.model';

export const SERVICE_OPTIONS = [
  'Residential Lockout',
  'Commercial Locks',
  'Car Keys',
  'Smart Lock Installation',
  'Rekey Service',
  'Storefront Glass Repair',
  'Window Repair',
  'Board-Up Service',
  'Glass Door Replacement',
  'Shower Glass Installation'
];

export const CITY_OPTIONS = [
  'Arlington',
  'Dallas',
  'Fort Worth',
  'Phoenix',
  'Scottsdale',
  'Tampa',
  'Miami',
  'Raleigh',
  'Charlotte',
  'Richmond'
];

export const STATE_OPTIONS = ['TX', 'AZ', 'FL', 'NC', 'VA'];

export const REGION_OPTIONS = ['South', 'Southwest', 'Southeast', 'Atlantic'];

export const MOCK_PROVIDERS: Provider[] = [
  {
    id: 1,
    fullName: 'Michael Torres',
    businessName: 'Arlington Lock Pros',
    phone: '(817) 555-1022',
    email: 'michael@arlingtonlockpros.com',
    serviceType: 'Locksmith',
    servicesOffered: ['Residential Lockout', 'Commercial Locks', 'Rekey Service'],
    city: 'Arlington',
    state: 'TX',
    zipCodes: ['76010', '76011', '76012'],
    region: 'South',
    emergencyService: true,
    availability: 'Weekdays + weekends',
    workingHours: '24/7',
    verificationStatus: 'Active',
    isActive: true,
    source: 'Google',
    yearsOfExperience: 12,
    notes: 'Strong reviews, reliable response time.',
    adminComments: 'Great candidate for hero placement.',
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-05-01T08:00:00Z',
    verifiedAt: '2026-02-02T13:30:00Z'
  },
  {
    id: 2,
    fullName: 'Emily Sanders',
    businessName: 'Metro Glass Fast Fix',
    phone: '(817) 555-1044',
    email: 'emily@metroglassfix.com',
    serviceType: 'Glass',
    servicesOffered: ['Window Repair', 'Storefront Glass Repair', 'Board-Up Service'],
    city: 'Arlington',
    state: 'TX',
    zipCodes: ['76013', '76014'],
    region: 'South',
    emergencyService: true,
    availability: 'Daily',
    workingHours: '6:00 AM - 11:00 PM',
    verificationStatus: 'Verified',
    isActive: true,
    source: 'Referral',
    yearsOfExperience: 9,
    createdAt: '2026-01-15T09:30:00Z',
    updatedAt: '2026-04-28T10:00:00Z',
    verifiedAt: '2026-02-04T12:15:00Z'
  },
  {
    id: 3,
    fullName: 'Brandon Lee',
    businessName: 'DFW Secure & Glass',
    phone: '(817) 555-1068',
    email: 'brandon@dfwsecureglass.com',
    serviceType: 'Both',
    servicesOffered: ['Car Keys', 'Smart Lock Installation', 'Glass Door Replacement'],
    city: 'Arlington',
    state: 'TX',
    zipCodes: ['76015', '76016'],
    region: 'South',
    emergencyService: true,
    availability: 'All week',
    workingHours: '24/7',
    verificationStatus: 'Active',
    isActive: true,
    source: 'Manual',
    yearsOfExperience: 14,
    createdAt: '2026-01-22T11:45:00Z',
    updatedAt: '2026-05-03T15:30:00Z',
    verifiedAt: '2026-02-10T10:00:00Z'
  },
  {
    id: 4,
    fullName: 'Sofia Ramirez',
    businessName: 'Dallas Rapid Locksmith',
    phone: '(214) 555-1120',
    email: 'sofia@dallasrapidlocksmith.com',
    serviceType: 'Locksmith',
    servicesOffered: ['Residential Lockout', 'Car Keys', 'Commercial Locks'],
    city: 'Dallas',
    state: 'TX',
    zipCodes: ['75201', '75204'],
    region: 'South',
    emergencyService: true,
    availability: 'Daily',
    workingHours: '24/7',
    verificationStatus: 'Active',
    isActive: true,
    source: 'Google',
    yearsOfExperience: 11,
    createdAt: '2026-02-01T10:10:00Z',
    updatedAt: '2026-04-30T10:10:00Z',
    verifiedAt: '2026-02-14T09:15:00Z'
  },
  {
    id: 5,
    fullName: 'Jordan Bell',
    businessName: 'Dallas Glass Rescue',
    phone: '(214) 555-1180',
    email: 'jordan@dallasglassrescue.com',
    serviceType: 'Glass',
    servicesOffered: ['Window Repair', 'Storefront Glass Repair'],
    city: 'Dallas',
    state: 'TX',
    zipCodes: ['75205', '75206'],
    region: 'South',
    emergencyService: false,
    availability: 'Weekdays',
    workingHours: '8:00 AM - 6:00 PM',
    verificationStatus: 'Contacted',
    isActive: true,
    source: 'Form',
    yearsOfExperience: 7,
    createdAt: '2026-02-05T12:00:00Z',
    updatedAt: '2026-04-18T09:00:00Z'
  },
  {
    id: 6,
    fullName: 'Nathan Miles',
    businessName: 'Fort Worth Lock Co',
    phone: '(682) 555-1208',
    email: 'nathan@fwlockco.com',
    serviceType: 'Locksmith',
    servicesOffered: ['Residential Lockout', 'Rekey Service', 'Smart Lock Installation'],
    city: 'Fort Worth',
    state: 'TX',
    zipCodes: ['76102', '76104'],
    region: 'South',
    emergencyService: true,
    availability: 'Daily',
    workingHours: '7:00 AM - 12:00 AM',
    verificationStatus: 'Verified',
    isActive: true,
    source: 'Referral',
    yearsOfExperience: 10,
    createdAt: '2026-02-10T11:00:00Z',
    updatedAt: '2026-04-21T10:00:00Z',
    verifiedAt: '2026-03-01T09:00:00Z'
  },
  {
    id: 7,
    fullName: 'Isabella Young',
    businessName: 'Phoenix Glass & Locks',
    phone: '(602) 555-1322',
    email: 'isabella@phxglasslocks.com',
    serviceType: 'Both',
    servicesOffered: ['Commercial Locks', 'Storefront Glass Repair', 'Board-Up Service'],
    city: 'Phoenix',
    state: 'AZ',
    zipCodes: ['85004', '85006'],
    region: 'Southwest',
    emergencyService: true,
    availability: 'All week',
    workingHours: '24/7',
    verificationStatus: 'Active',
    isActive: true,
    source: 'Google',
    yearsOfExperience: 13,
    createdAt: '2026-02-14T13:00:00Z',
    updatedAt: '2026-05-02T07:30:00Z',
    verifiedAt: '2026-02-26T09:30:00Z'
  },
  {
    id: 8,
    fullName: 'Alex Chen',
    businessName: 'Scottsdale Key & Pane',
    phone: '(480) 555-1440',
    email: 'alex@scottsdalekeypane.com',
    serviceType: 'Both',
    servicesOffered: ['Car Keys', 'Window Repair', 'Glass Door Replacement'],
    city: 'Scottsdale',
    state: 'AZ',
    zipCodes: ['85251', '85257'],
    region: 'Southwest',
    emergencyService: false,
    availability: 'Weekdays + Sat',
    workingHours: '8:00 AM - 8:00 PM',
    verificationStatus: 'Verified',
    isActive: true,
    source: 'Manual',
    yearsOfExperience: 8,
    createdAt: '2026-02-18T16:00:00Z',
    updatedAt: '2026-04-16T11:00:00Z',
    verifiedAt: '2026-03-05T11:20:00Z'
  },
  {
    id: 9,
    fullName: 'Carmen Diaz',
    businessName: 'Tampa 24H Locksmith',
    phone: '(813) 555-1515',
    email: 'carmen@tampa24hlocksmith.com',
    serviceType: 'Locksmith',
    servicesOffered: ['Residential Lockout', 'Car Keys', 'Rekey Service'],
    city: 'Tampa',
    state: 'FL',
    zipCodes: ['33602', '33606'],
    region: 'Southeast',
    emergencyService: true,
    availability: 'Daily',
    workingHours: '24/7',
    verificationStatus: 'Active',
    isActive: true,
    source: 'Form',
    yearsOfExperience: 15,
    createdAt: '2026-02-20T10:40:00Z',
    updatedAt: '2026-05-05T07:40:00Z',
    verifiedAt: '2026-03-08T08:00:00Z'
  },
  {
    id: 10,
    fullName: 'Greg Foster',
    businessName: 'Suncoast Glass Team',
    phone: '(813) 555-1555',
    email: 'greg@suncoastglassteam.com',
    serviceType: 'Glass',
    servicesOffered: ['Window Repair', 'Shower Glass Installation'],
    city: 'Tampa',
    state: 'FL',
    zipCodes: ['33607'],
    region: 'Southeast',
    emergencyService: false,
    availability: 'Weekdays',
    workingHours: '8:00 AM - 5:00 PM',
    verificationStatus: 'New',
    isActive: false,
    source: 'Referral',
    yearsOfExperience: 6,
    createdAt: '2026-03-03T09:00:00Z',
    updatedAt: '2026-03-03T09:00:00Z'
  },
  {
    id: 11,
    fullName: 'Mia Patel',
    businessName: 'Miami Elite Glass',
    phone: '(305) 555-1612',
    email: 'mia@miamieliteglass.com',
    serviceType: 'Glass',
    servicesOffered: ['Storefront Glass Repair', 'Glass Door Replacement', 'Board-Up Service'],
    city: 'Miami',
    state: 'FL',
    zipCodes: ['33131', '33132'],
    region: 'Southeast',
    emergencyService: true,
    availability: 'Daily',
    workingHours: '24/7',
    verificationStatus: 'Verified',
    isActive: true,
    source: 'Google',
    yearsOfExperience: 12,
    createdAt: '2026-03-08T14:30:00Z',
    updatedAt: '2026-04-22T13:00:00Z',
    verifiedAt: '2026-03-20T11:00:00Z'
  },
  {
    id: 12,
    fullName: 'Owen Clark',
    businessName: 'Raleigh Lock & Key',
    phone: '(919) 555-1770',
    email: 'owen@raleighlockkey.com',
    serviceType: 'Locksmith',
    servicesOffered: ['Commercial Locks', 'Rekey Service'],
    city: 'Raleigh',
    state: 'NC',
    zipCodes: ['27601'],
    region: 'Atlantic',
    emergencyService: false,
    availability: 'Weekdays',
    workingHours: '9:00 AM - 6:00 PM',
    verificationStatus: 'Contacted',
    isActive: true,
    source: 'Manual',
    yearsOfExperience: 5,
    createdAt: '2026-03-12T09:20:00Z',
    updatedAt: '2026-04-10T09:20:00Z'
  },
  {
    id: 13,
    fullName: 'Ava Simmons',
    businessName: 'Charlotte Glass Aid',
    phone: '(704) 555-1811',
    email: 'ava@charlotteglassaid.com',
    serviceType: 'Glass',
    servicesOffered: ['Window Repair', 'Glass Door Replacement'],
    city: 'Charlotte',
    state: 'NC',
    zipCodes: ['28202'],
    region: 'Atlantic',
    emergencyService: true,
    availability: 'Daily',
    workingHours: '7:00 AM - 10:00 PM',
    verificationStatus: 'Verified',
    isActive: true,
    source: 'Referral',
    yearsOfExperience: 9,
    createdAt: '2026-03-18T15:00:00Z',
    updatedAt: '2026-04-25T08:45:00Z',
    verifiedAt: '2026-03-30T10:10:00Z'
  },
  {
    id: 14,
    fullName: 'Liam Brooks',
    businessName: 'Richmond Home Locksmith',
    phone: '(804) 555-1905',
    email: 'liam@richmondhomelocksmith.com',
    serviceType: 'Locksmith',
    servicesOffered: ['Residential Lockout', 'Smart Lock Installation'],
    city: 'Richmond',
    state: 'VA',
    zipCodes: ['23219'],
    region: 'Atlantic',
    emergencyService: false,
    availability: 'Weekdays + Sat',
    workingHours: '8:30 AM - 7:00 PM',
    verificationStatus: 'New',
    isActive: true,
    source: 'Form',
    yearsOfExperience: 4,
    createdAt: '2026-03-28T12:20:00Z',
    updatedAt: '2026-03-28T12:20:00Z'
  }
];

export const MOCK_APPLICATIONS: ProviderApplication[] = [
  {
    id: 101,
    fullName: 'Noah Price',
    businessName: 'Phoenix Smart Locks',
    phone: '(602) 555-2001',
    email: 'noah@phxsmartlocks.com',
    serviceType: 'Locksmith',
    servicesOffered: ['Smart Lock Installation', 'Car Keys'],
    citiesCovered: ['Phoenix', 'Scottsdale'],
    city: 'Phoenix',
    state: 'AZ',
    zipCodes: ['85008', '85009'],
    yearsOfExperience: 7,
    emergencyService: true,
    workingHours: '24/7',
    message: 'We can handle overflow and after-hours calls.',
    source: 'Form',
    status: 'Pending',
    submittedAt: '2026-05-02T09:35:00Z',
    licenseFileName: 'noah-price-license.pdf'
  },
  {
    id: 102,
    fullName: 'Grace Kim',
    businessName: 'Arlington Precision Glass',
    phone: '(817) 555-2030',
    email: 'grace@precisionglassarlington.com',
    serviceType: 'Glass',
    servicesOffered: ['Storefront Glass Repair', 'Board-Up Service', 'Window Repair'],
    citiesCovered: ['Arlington'],
    city: 'Arlington',
    state: 'TX',
    zipCodes: ['76017', '76018'],
    yearsOfExperience: 11,
    emergencyService: true,
    workingHours: '6:00 AM - 10:00 PM',
    message: 'Interested in premium placement in Arlington pages.',
    source: 'Form',
    status: 'Pending',
    submittedAt: '2026-05-03T14:10:00Z'
  },
  {
    id: 103,
    fullName: 'Tyler Moore',
    businessName: 'Tampa Auto Key Tech',
    phone: '(813) 555-2068',
    email: 'tyler@tampaautokeytech.com',
    serviceType: 'Locksmith',
    servicesOffered: ['Car Keys', 'Residential Lockout'],
    citiesCovered: ['Tampa'],
    city: 'Tampa',
    state: 'FL',
    zipCodes: ['33609'],
    yearsOfExperience: 5,
    emergencyService: false,
    workingHours: '9:00 AM - 8:00 PM',
    message: 'Can join immediately for ad campaigns.',
    source: 'Form',
    status: 'Pending',
    submittedAt: '2026-05-04T11:45:00Z'
  },
  {
    id: 104,
    fullName: 'Hannah Reed',
    businessName: 'Raleigh Glass Hub',
    phone: '(919) 555-2112',
    email: 'hannah@raleighglasshub.com',
    serviceType: 'Glass',
    servicesOffered: ['Window Repair', 'Shower Glass Installation'],
    citiesCovered: ['Raleigh'],
    city: 'Raleigh',
    state: 'NC',
    zipCodes: ['27603', '27604'],
    yearsOfExperience: 6,
    emergencyService: false,
    workingHours: '8:00 AM - 6:00 PM',
    message: 'Need more details about onboarding process.',
    source: 'Form',
    status: 'More Info Requested',
    submittedAt: '2026-05-01T08:15:00Z'
  }
];
